# Generated by Django 4.0.1 on 2022-01-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_featurs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurs',
            options={'verbose_name': 'Featurs', 'verbose_name_plural': 'Featuring'},
        ),
    ]
